name: aria2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: D:\m64-102
        key: m64-102
    - name: Setup Toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL http://msystem.waw.pl/x265/mingw-gcc102-20200925.7z
        &'C:\Program Files\7-Zip\7z.exe' x *.7z -o'D:'
    - name: Prepare
      run: |
        git config --global core.autocrlf false
        C:\msys64\usr\bin\bash -lc "sed -i 's/.tar.zst/.tar.xz/' /etc/makepkg.conf"
        curl -OL https://github.com/nyfair/MSYS2-packages/releases/download/dev/zlib-dev-1.2.11-1-x86_64.pkg.tar.zst
        C:\msys64\usr\bin\bash -lc "pacman -U /d/a/MSYS2-packages/MSYS2-packages/*.zst --noconfirm"
    - uses: actions/checkout@v2
    - name: Build
      run: |
        C:\msys64\usr\bin\bash -lc 'export PATH=/usr/local/bin:/usr/bin:/opt/bin:/d/m64-102/bin; cd /d/a/MSYS2-packages/MSYS2-packages/aria2; makepkg'
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: aria2/*pkg.tar*
        tag: latest
        overwrite: true
        file_glob: true
